
OTHER_FILES += \
ATCM-template-form-class/generate.pl \
ATCM-template-form-class/page.cpp \
ATCM-template-form-class/page.h \
ATCM-template-form-class/page.ui \
ATCM-template-form-class/wizard.xml \
ATCM-template-project-AnyTPAC043/config/Crosstable.csv \
ATCM-template-project-AnyTPAC043/config/crosstable.cpp \
ATCM-template-project-AnyTPAC043/config/crosstable.h \
ATCM-template-project-AnyTPAC043/config/splash.png \
ATCM-template-project-AnyTPAC043/config/system.ini \
ATCM-template-project-AnyTPAC043/config/trend1.csv \
ATCM-template-project-AnyTPAC043/console.png \
ATCM-template-project-AnyTPAC043/template.pri \
ATCM-template-project-AnyTPAC043/wizard.xml \
ATCM-template-project-AnyTPAC070/config/Crosstable.csv \
ATCM-template-project-AnyTPAC070/config/crosstable.cpp \
ATCM-template-project-AnyTPAC070/config/crosstable.h \
ATCM-template-project-AnyTPAC070/config/splash.png \
ATCM-template-project-AnyTPAC070/config/system.ini \
ATCM-template-project-AnyTPAC070/config/trend1.csv \
ATCM-template-project-AnyTPAC070/console.png \
ATCM-template-project-AnyTPAC070/template.pri \
ATCM-template-project-AnyTPAC070/wizard.xml \
ATCM-template-project-TP1043_01_A/config/Crosstable.csv \
ATCM-template-project-TP1043_01_A/config/crosstable.cpp \
ATCM-template-project-TP1043_01_A/config/crosstable.h \
ATCM-template-project-TP1043_01_A/config/splash.png \
ATCM-template-project-TP1043_01_A/config/system.ini \
ATCM-template-project-TP1043_01_A/config/trend1.csv \
ATCM-template-project-TP1043_01_A/console.png \
ATCM-template-project-TP1043_01_A/template.pri \
ATCM-template-project-TP1043_01_A/wizard.xml \
ATCM-template-project-TP1043_02_A/config/Crosstable.csv \
ATCM-template-project-TP1043_02_A/config/crosstable.cpp \
ATCM-template-project-TP1043_02_A/config/crosstable.h \
ATCM-template-project-TP1043_02_A/config/splash.png \
ATCM-template-project-TP1043_02_A/config/system.ini \
ATCM-template-project-TP1043_02_A/config/trend1.csv \
ATCM-template-project-TP1043_02_A/console.png \
ATCM-template-project-TP1043_02_A/template.pri \
ATCM-template-project-TP1043_02_A/wizard.xml \
ATCM-template-project-TP1043_02_B/config/Crosstable.csv \
ATCM-template-project-TP1043_02_B/config/crosstable.cpp \
ATCM-template-project-TP1043_02_B/config/crosstable.h \
ATCM-template-project-TP1043_02_B/config/splash.png \
ATCM-template-project-TP1043_02_B/config/system.ini \
ATCM-template-project-TP1043_02_B/config/trend1.csv \
ATCM-template-project-TP1043_02_B/console.png \
ATCM-template-project-TP1043_02_B/template.pri \
ATCM-template-project-TP1043_02_B/wizard.xml \
ATCM-template-project-TP1070_01_A/config/Crosstable.csv \
ATCM-template-project-TP1070_01_A/config/crosstable.cpp \
ATCM-template-project-TP1070_01_A/config/crosstable.h \
ATCM-template-project-TP1070_01_A/config/splash.png \
ATCM-template-project-TP1070_01_A/config/system.ini \
ATCM-template-project-TP1070_01_A/config/trend1.csv \
ATCM-template-project-TP1070_01_A/console.png \
ATCM-template-project-TP1070_01_A/template.pri \
ATCM-template-project-TP1070_01_A/wizard.xml \
ATCM-template-project-TP1070_01_B/config/Crosstable.csv \
ATCM-template-project-TP1070_01_B/config/crosstable.cpp \
ATCM-template-project-TP1070_01_B/config/crosstable.h \
ATCM-template-project-TP1070_01_B/config/splash.png \
ATCM-template-project-TP1070_01_B/config/system.ini \
ATCM-template-project-TP1070_01_B/config/trend1.csv \
ATCM-template-project-TP1070_01_B/console.png \
ATCM-template-project-TP1070_01_B/template.pri \
ATCM-template-project-TP1070_01_B/wizard.xml \
ATCM-template-project-TP1070_01_C/config/Crosstable.csv \
ATCM-template-project-TP1070_01_C/config/crosstable.cpp \
ATCM-template-project-TP1070_01_C/config/crosstable.h \
ATCM-template-project-TP1070_01_C/config/splash.png \
ATCM-template-project-TP1070_01_C/config/system.ini \
ATCM-template-project-TP1070_01_C/config/trend1.csv \
ATCM-template-project-TP1070_01_C/console.png \
ATCM-template-project-TP1070_01_C/template.pri \
ATCM-template-project-TP1070_01_C/wizard.xml \
ATCM-template-project-TP1070_02_F/automation.cpp \
ATCM-template-project-TP1070_02_F/config/Crosstable.csv \
ATCM-template-project-TP1070_02_F/config/crosstable.cpp \
ATCM-template-project-TP1070_02_F/config/crosstable.h \
ATCM-template-project-TP1070_02_F/config/splash.png \
ATCM-template-project-TP1070_02_F/config/system.ini \
ATCM-template-project-TP1070_02_F/config/trend1.csv \
ATCM-template-project-TP1070_02_F/console.png \
ATCM-template-project-TP1070_02_F/template.pri \
ATCM-template-project-TP1070_02_F/wizard.xml \
ATCM-template-project-TPAC1005/config/Crosstable.csv \
ATCM-template-project-TPAC1005/config/crosstable.cpp \
ATCM-template-project-TPAC1005/config/crosstable.h \
ATCM-template-project-TPAC1005/config/splash.png \
ATCM-template-project-TPAC1005/config/system.ini \
ATCM-template-project-TPAC1005/config/trend1.csv \
ATCM-template-project-TPAC1005/console.png \
ATCM-template-project-TPAC1005/template.pri \
ATCM-template-project-TPAC1005/wizard.xml \
ATCM-template-project-TPAC1007_03/config/Crosstable.csv \
ATCM-template-project-TPAC1007_03/config/crosstable.cpp \
ATCM-template-project-TPAC1007_03/config/crosstable.h \
ATCM-template-project-TPAC1007_03/config/splash.png \
ATCM-template-project-TPAC1007_03/config/system.ini \
ATCM-template-project-TPAC1007_03/config/trend1.csv \
ATCM-template-project-TPAC1007_03/console.png \
ATCM-template-project-TPAC1007_03/template.pri \
ATCM-template-project-TPAC1007_03/wizard.xml \
ATCM-template-project-TPAC1007_04_AA/config/Crosstable.csv \
ATCM-template-project-TPAC1007_04_AA/config/crosstable.cpp \
ATCM-template-project-TPAC1007_04_AA/config/crosstable.h \
ATCM-template-project-TPAC1007_04_AA/config/splash.png \
ATCM-template-project-TPAC1007_04_AA/config/system.ini \
ATCM-template-project-TPAC1007_04_AA/config/trend1.csv \
ATCM-template-project-TPAC1007_04_AA/console.png \
ATCM-template-project-TPAC1007_04_AA/template.pri \
ATCM-template-project-TPAC1007_04_AA/wizard.xml \
ATCM-template-project-TPAC1007_04_AB/config/Crosstable.csv \
ATCM-template-project-TPAC1007_04_AB/config/crosstable.cpp \
ATCM-template-project-TPAC1007_04_AB/config/crosstable.h \
ATCM-template-project-TPAC1007_04_AB/config/splash.png \
ATCM-template-project-TPAC1007_04_AB/config/system.ini \
ATCM-template-project-TPAC1007_04_AB/config/trend1.csv \
ATCM-template-project-TPAC1007_04_AB/console.png \
ATCM-template-project-TPAC1007_04_AB/template.pri \
ATCM-template-project-TPAC1007_04_AB/wizard.xml \
ATCM-template-project-TPAC1007_04_AC/config/Crosstable.csv \
ATCM-template-project-TPAC1007_04_AC/config/crosstable.cpp \
ATCM-template-project-TPAC1007_04_AC/config/crosstable.h \
ATCM-template-project-TPAC1007_04_AC/config/splash.png \
ATCM-template-project-TPAC1007_04_AC/config/system.ini \
ATCM-template-project-TPAC1007_04_AC/config/trend1.csv \
ATCM-template-project-TPAC1007_04_AC/console.png \
ATCM-template-project-TPAC1007_04_AC/template.pri \
ATCM-template-project-TPAC1007_04_AC/wizard.xml \
ATCM-template-project-TPAC1007_04_AD/config/Crosstable.csv \
ATCM-template-project-TPAC1007_04_AD/config/crosstable.cpp \
ATCM-template-project-TPAC1007_04_AD/config/crosstable.h \
ATCM-template-project-TPAC1007_04_AD/config/splash.png \
ATCM-template-project-TPAC1007_04_AD/config/system.ini \
ATCM-template-project-TPAC1007_04_AD/config/trend1.csv \
ATCM-template-project-TPAC1007_04_AD/console.png \
ATCM-template-project-TPAC1007_04_AD/template.pri \
ATCM-template-project-TPAC1007_04_AD/wizard.xml \
ATCM-template-project-TPAC1007_04_AE/config/Crosstable.csv \
ATCM-template-project-TPAC1007_04_AE/config/crosstable.cpp \
ATCM-template-project-TPAC1007_04_AE/config/crosstable.h \
ATCM-template-project-TPAC1007_04_AE/config/splash.png \
ATCM-template-project-TPAC1007_04_AE/config/system.ini \
ATCM-template-project-TPAC1007_04_AE/config/trend1.csv \
ATCM-template-project-TPAC1007_04_AE/console.png \
ATCM-template-project-TPAC1007_04_AE/template.pri \
ATCM-template-project-TPAC1007_04_AE/wizard.xml \
ATCM-template-project-TPAC1008_02_AA/config/Crosstable.csv \
ATCM-template-project-TPAC1008_02_AA/config/crosstable.cpp \
ATCM-template-project-TPAC1008_02_AA/config/crosstable.h \
ATCM-template-project-TPAC1008_02_AA/config/iomap0.cmg \
ATCM-template-project-TPAC1008_02_AA/config/network0.cmg \
ATCM-template-project-TPAC1008_02_AA/config/splash.png \
ATCM-template-project-TPAC1008_02_AA/config/system.ini \
ATCM-template-project-TPAC1008_02_AA/config/trend1.csv \
ATCM-template-project-TPAC1008_02_AA/console.png \
ATCM-template-project-TPAC1008_02_AA/template.pri \
ATCM-template-project-TPAC1008_02_AA/wizard.xml \
ATCM-template-project-TPAC1008_02_AB/config/Crosstable.csv \
ATCM-template-project-TPAC1008_02_AB/config/crosstable.cpp \
ATCM-template-project-TPAC1008_02_AB/config/crosstable.h \
ATCM-template-project-TPAC1008_02_AB/config/iomap0.cmg \
ATCM-template-project-TPAC1008_02_AB/config/network0.cmg \
ATCM-template-project-TPAC1008_02_AB/config/splash.png \
ATCM-template-project-TPAC1008_02_AB/config/system.ini \
ATCM-template-project-TPAC1008_02_AB/config/trend1.csv \
ATCM-template-project-TPAC1008_02_AB/console.png \
ATCM-template-project-TPAC1008_02_AB/template.pri \
ATCM-template-project-TPAC1008_02_AB/wizard.xml \
ATCM-template-project-TPAC1008_02_AD/config/Crosstable.csv \
ATCM-template-project-TPAC1008_02_AD/config/crosstable.cpp \
ATCM-template-project-TPAC1008_02_AD/config/crosstable.h \
ATCM-template-project-TPAC1008_02_AD/config/iomap0.cmg \
ATCM-template-project-TPAC1008_02_AD/config/network0.cmg \
ATCM-template-project-TPAC1008_02_AD/config/splash.png \
ATCM-template-project-TPAC1008_02_AD/config/system.ini \
ATCM-template-project-TPAC1008_02_AD/config/trend1.csv \
ATCM-template-project-TPAC1008_02_AD/console.png \
ATCM-template-project-TPAC1008_02_AD/template.pri \
ATCM-template-project-TPAC1008_02_AD/wizard.xml \
ATCM-template-project-TPAC1008_02_AE/config/Crosstable.csv \
ATCM-template-project-TPAC1008_02_AE/config/crosstable.cpp \
ATCM-template-project-TPAC1008_02_AE/config/crosstable.h \
ATCM-template-project-TPAC1008_02_AE/config/iomap0.cmg \
ATCM-template-project-TPAC1008_02_AE/config/network0.cmg \
ATCM-template-project-TPAC1008_02_AE/config/splash.png \
ATCM-template-project-TPAC1008_02_AE/config/system.ini \
ATCM-template-project-TPAC1008_02_AE/config/trend1.csv \
ATCM-template-project-TPAC1008_02_AE/console.png \
ATCM-template-project-TPAC1008_02_AE/template.pri \
ATCM-template-project-TPAC1008_02_AE/wizard.xml \
ATCM-template-project-TPAC1008_02_AF/config/Crosstable.csv \
ATCM-template-project-TPAC1008_02_AF/config/crosstable.cpp \
ATCM-template-project-TPAC1008_02_AF/config/crosstable.h \
ATCM-template-project-TPAC1008_02_AF/config/iomap0.cmg \
ATCM-template-project-TPAC1008_02_AF/config/network0.cmg \
ATCM-template-project-TPAC1008_02_AF/config/splash.png \
ATCM-template-project-TPAC1008_02_AF/config/system.ini \
ATCM-template-project-TPAC1008_02_AF/config/trend1.csv \
ATCM-template-project-TPAC1008_02_AF/console.png \
ATCM-template-project-TPAC1008_02_AF/template.pri \
ATCM-template-project-TPAC1008_02_AF/wizard.xml \
ATCM-template-project-TPAC1008_03_AC/automation.cpp \
ATCM-template-project-TPAC1008_03_AC/config/Crosstable.csv \
ATCM-template-project-TPAC1008_03_AC/config/crosstable.cpp \
ATCM-template-project-TPAC1008_03_AC/config/crosstable.h \
ATCM-template-project-TPAC1008_03_AC/config/iomap0.cmg \
ATCM-template-project-TPAC1008_03_AC/config/network0.cmg \
ATCM-template-project-TPAC1008_03_AC/config/splash.png \
ATCM-template-project-TPAC1008_03_AC/config/system.ini \
ATCM-template-project-TPAC1008_03_AC/config/trend1.csv \
ATCM-template-project-TPAC1008_03_AC/console.png \
ATCM-template-project-TPAC1008_03_AC/template.pri \
ATCM-template-project-TPAC1008_03_AC/wizard.xml \
ATCM-template-project-TPAC1008_03_AD/automation.cpp \
ATCM-template-project-TPAC1008_03_AD/config/Crosstable.csv \
ATCM-template-project-TPAC1008_03_AD/config/crosstable.cpp \
ATCM-template-project-TPAC1008_03_AD/config/crosstable.h \
ATCM-template-project-TPAC1008_03_AD/config/iomap0.cmg \
ATCM-template-project-TPAC1008_03_AD/config/network0.cmg \
ATCM-template-project-TPAC1008_03_AD/config/splash.png \
ATCM-template-project-TPAC1008_03_AD/config/system.ini \
ATCM-template-project-TPAC1008_03_AD/config/trend1.csv \
ATCM-template-project-TPAC1008_03_AD/console.png \
ATCM-template-project-TPAC1008_03_AD/template.pri \
ATCM-template-project-TPAC1008_03_AD/wizard.xml \
ATCM-template-project-TPLC050_01_AA/config/Crosstable.csv \
ATCM-template-project-TPLC050_01_AA/config/crosstable.cpp \
ATCM-template-project-TPLC050_01_AA/config/crosstable.h \
ATCM-template-project-TPLC050_01_AA/config/splash.png \
ATCM-template-project-TPLC050_01_AA/config/system.ini \
ATCM-template-project-TPLC050_01_AA/config/trend1.csv \
ATCM-template-project-TPLC050_01_AA/console.png \
ATCM-template-project-TPLC050_01_AA/template.pri \
ATCM-template-project-TPLC050_01_AA/wizard.xml \
ATCM-template-project-TPLC100_01_AA/config/Crosstable.csv \
ATCM-template-project-TPLC100_01_AA/config/crosstable.cpp \
ATCM-template-project-TPLC100_01_AA/config/crosstable.h \
ATCM-template-project-TPLC100_01_AA/config/iomap0.cmg \
ATCM-template-project-TPLC100_01_AA/config/network0.cmg \
ATCM-template-project-TPLC100_01_AA/config/splash.png \
ATCM-template-project-TPLC100_01_AA/config/system.ini \
ATCM-template-project-TPLC100_01_AA/config/trend1.csv \
ATCM-template-project-TPLC100_01_AA/console.png \
ATCM-template-project-TPLC100_01_AA/template.pri \
ATCM-template-project-TPLC100_01_AA/wizard.xml \
ATCM-template-project-TPLC100_01_AB/config/Crosstable.csv \
ATCM-template-project-TPLC100_01_AB/config/crosstable.cpp \
ATCM-template-project-TPLC100_01_AB/config/crosstable.h \
ATCM-template-project-TPLC100_01_AB/config/iomap0.cmg \
ATCM-template-project-TPLC100_01_AB/config/network0.cmg \
ATCM-template-project-TPLC100_01_AB/config/splash.png \
ATCM-template-project-TPLC100_01_AB/config/system.ini \
ATCM-template-project-TPLC100_01_AB/config/trend1.csv \
ATCM-template-project-TPLC100_01_AB/console.png \
ATCM-template-project-TPLC100_01_AB/template.pri \
ATCM-template-project-TPLC100_01_AB/wizard.xml \
ATCM-template-project-TPX1070_03_D/automation.cpp \
ATCM-template-project-TPX1070_03_D/config/Crosstable.csv \
ATCM-template-project-TPX1070_03_D/config/crosstable.cpp \
ATCM-template-project-TPX1070_03_D/config/crosstable.h \
ATCM-template-project-TPX1070_03_D/config/splash.png \
ATCM-template-project-TPX1070_03_D/config/system.ini \
ATCM-template-project-TPX1070_03_D/config/trend1.csv \
ATCM-template-project-TPX1070_03_D/console.png \
ATCM-template-project-TPX1070_03_D/template.pri \
ATCM-template-project-TPX1070_03_D/wizard.xml \
ATCM-template-project-TPX1070_03_E/automation.cpp \
ATCM-template-project-TPX1070_03_E/config/Crosstable.csv \
ATCM-template-project-TPX1070_03_E/config/crosstable.cpp \
ATCM-template-project-TPX1070_03_E/config/crosstable.h \
ATCM-template-project-TPX1070_03_E/config/splash.png \
ATCM-template-project-TPX1070_03_E/config/system.ini \
ATCM-template-project-TPX1070_03_E/config/trend1.csv \
ATCM-template-project-TPX1070_03_E/console.png \
ATCM-template-project-TPX1070_03_E/template.pri \
ATCM-template-project-TPX1070_03_E/wizard.xml \
ATCM-template-project/automation.cpp \
ATCM-template-project/automation.h \
ATCM-template-project/check_cross_var.pl \
ATCM-template-project/check_systemini.pl \
ATCM-template-project/cleanmissingpage.pl \
ATCM-template-project/common.pri \
ATCM-template-project/connectbutton.pl \
ATCM-template-project/console.png \
ATCM-template-project/defaultfont.pl \
ATCM-template-project/fonts/put.your.fonts.here \
ATCM-template-project/icons/put.your.icons.here \
ATCM-template-project/img/3d_bar_chart.png \
ATCM-template-project/img/Abort.png \
ATCM-template-project/img/About.png \
ATCM-template-project/img/Accounting.png \
ATCM-template-project/img/Add.png \
ATCM-template-project/img/Address_book.png \
ATCM-template-project/img/Alarm.png \
ATCM-template-project/img/Alarm_clock.png \
ATCM-template-project/img/Alert.png \
ATCM-template-project/img/Alien.png \
ATCM-template-project/img/Anchor.png \
ATCM-template-project/img/Application.png \
ATCM-template-project/img/Apply.png \
ATCM-template-project/img/Back.png \
ATCM-template-project/img/Bad_mark.png \
ATCM-template-project/img/Bee.png \
ATCM-template-project/img/Black_bookmark.png \
ATCM-template-project/img/Black_pin.png \
ATCM-template-project/img/Black_tag.png \
ATCM-template-project/img/Blog.png \
ATCM-template-project/img/Blue_bookmark.png \
ATCM-template-project/img/Blue_key.png \
ATCM-template-project/img/Blue_pin.png \
ATCM-template-project/img/Blue_tag.png \
ATCM-template-project/img/Bomb.png \
ATCM-template-project/img/Bookmark.png \
ATCM-template-project/img/Boss.png \
ATCM-template-project/img/Bottom.png \
ATCM-template-project/img/Briefcase.png \
ATCM-template-project/img/Brush.png \
ATCM-template-project/img/Bubble.png \
ATCM-template-project/img/Buy.png \
ATCM-template-project/img/CD.png \
ATCM-template-project/img/Calculator.png \
ATCM-template-project/img/Calendar.png \
ATCM-template-project/img/Camera.png \
ATCM-template-project/img/Car_key.png \
ATCM-template-project/img/Chess.png \
ATCM-template-project/img/Chess1.png \
ATCM-template-project/img/Chess2.png \
ATCM-template-project/img/Clear.png \
ATCM-template-project/img/Clipboard.png \
ATCM-template-project/img/Clock.png \
ATCM-template-project/img/Close.png \
ATCM-template-project/img/Coin.png \
ATCM-template-project/img/Comment.png \
ATCM-template-project/img/Company.png \
ATCM-template-project/img/Compass.png \
ATCM-template-project/img/Component.png \
ATCM-template-project/img/Computer.png \
ATCM-template-project/img/Copy.png \
ATCM-template-project/img/Create.png \
ATCM-template-project/img/Cut.png \
ATCM-template-project/img/Danger.png \
ATCM-template-project/img/Database.png \
ATCM-template-project/img/Delete.png \
ATCM-template-project/img/Delivery.png \
ATCM-template-project/img/Diagram.png \
ATCM-template-project/img/Dial.png \
ATCM-template-project/img/Disaster.png \
ATCM-template-project/img/Display.png \
ATCM-template-project/img/Dollar.png \
ATCM-template-project/img/Door.png \
ATCM-template-project/img/Down.png \
ATCM-template-project/img/Download.png \
ATCM-template-project/img/Downloads_folder.png \
ATCM-template-project/img/E-mail.png \
ATCM-template-project/img/Earth.png \
ATCM-template-project/img/Eject.png \
ATCM-template-project/img/Equipment.png \
ATCM-template-project/img/Erase.png \
ATCM-template-project/img/Error.png \
ATCM-template-project/img/Euro.png \
ATCM-template-project/img/Exit.png \
ATCM-template-project/img/Expand.png \
ATCM-template-project/img/Eye.png \
ATCM-template-project/img/Fall.png \
ATCM-template-project/img/Fast-forward.png \
ATCM-template-project/img/Favourites.png \
ATCM-template-project/img/Female.png \
ATCM-template-project/img/Female_symbol.png \
ATCM-template-project/img/Film.png \
ATCM-template-project/img/Filter.png \
ATCM-template-project/img/Find.png \
ATCM-template-project/img/First.png \
ATCM-template-project/img/First_record.png \
ATCM-template-project/img/Flag.png \
ATCM-template-project/img/Flash_drive.png \
ATCM-template-project/img/Folder.png \
ATCM-template-project/img/Forbidden.png \
ATCM-template-project/img/Forward.png \
ATCM-template-project/img/Free_bsd.png \
ATCM-template-project/img/Gift.png \
ATCM-template-project/img/Globe.png \
ATCM-template-project/img/Go.png \
ATCM-template-project/img/Go_back.png \
ATCM-template-project/img/Go_forward.png \
ATCM-template-project/img/Good_mark.png \
ATCM-template-project/img/GprsOff.png \
ATCM-template-project/img/GprsOn.png \
ATCM-template-project/img/Green_bookmark.png \
ATCM-template-project/img/Green_pin.png \
ATCM-template-project/img/Green_tag.png \
ATCM-template-project/img/Hard_disk.png \
ATCM-template-project/img/Heart.png \
ATCM-template-project/img/Help.png \
ATCM-template-project/img/Help_book.png \
ATCM-template-project/img/Help_book_3d.png \
ATCM-template-project/img/Hint.png \
ATCM-template-project/img/History.png \
ATCM-template-project/img/Home.png \
ATCM-template-project/img/Hourglass.png \
ATCM-template-project/img/How-to.png \
ATCM-template-project/img/Hungup.png \
ATCM-template-project/img/In-yang.png \
ATCM-template-project/img/Info.png \
ATCM-template-project/img/Iphone.png \
ATCM-template-project/img/Key.png \
ATCM-template-project/img/Landscape.png \
ATCM-template-project/img/Last.png \
ATCM-template-project/img/Last_recor.png \
ATCM-template-project/img/LedOff.png \
ATCM-template-project/img/LedOn.png \
ATCM-template-project/img/Left-right.png \
ATCM-template-project/img/Letter.png \
ATCM-template-project/img/Lightning.png \
ATCM-template-project/img/Liner.png \
ATCM-template-project/img/Linux.png \
ATCM-template-project/img/List.png \
ATCM-template-project/img/Load.png \
ATCM-template-project/img/Lock.png \
ATCM-template-project/img/Low_rating.png \
ATCM-template-project/img/Magic_wand.png \
ATCM-template-project/img/Mail.png \
ATCM-template-project/img/Male.png \
ATCM-template-project/img/Male_symbol.png \
ATCM-template-project/img/Medium_rating.png \
ATCM-template-project/img/Message.png \
ATCM-template-project/img/Minus.png \
ATCM-template-project/img/Mobile-phone.png \
ATCM-template-project/img/Modify.png \
ATCM-template-project/img/Move.png \
ATCM-template-project/img/Movie.png \
ATCM-template-project/img/Music.png \
ATCM-template-project/img/Mute.png \
ATCM-template-project/img/Network_connection.png \
ATCM-template-project/img/New.png \
ATCM-template-project/img/New_document.png \
ATCM-template-project/img/Next.png \
ATCM-template-project/img/Next_track.png \
ATCM-template-project/img/No-entry.png \
ATCM-template-project/img/No.png \
ATCM-template-project/img/Notes.png \
ATCM-template-project/img/OK.png \
ATCM-template-project/img/Paste.png \
ATCM-template-project/img/Pause.png \
ATCM-template-project/img/People.png \
ATCM-template-project/img/Percent.png \
ATCM-template-project/img/Person.png \
ATCM-template-project/img/Phone.png \
ATCM-template-project/img/Phone_number.png \
ATCM-template-project/img/Picture.png \
ATCM-template-project/img/Pie_chart.png \
ATCM-template-project/img/Pinion.png \
ATCM-template-project/img/Play-music.png \
ATCM-template-project/img/Play.png \
ATCM-template-project/img/Playback.png \
ATCM-template-project/img/Plus.png \
ATCM-template-project/img/Portrait.png \
ATCM-template-project/img/Previous.png \
ATCM-template-project/img/Previous_record.png \
ATCM-template-project/img/Print.png \
ATCM-template-project/img/Problem.png \
ATCM-template-project/img/Question.png \
ATCM-template-project/img/Radiation.png \
ATCM-template-project/img/Raise.png \
ATCM-template-project/img/Record.png \
ATCM-template-project/img/Red_bookmark.png \
ATCM-template-project/img/Red_mark.png \
ATCM-template-project/img/Red_pin.png \
ATCM-template-project/img/Red_star.png \
ATCM-template-project/img/Red_tag.png \
ATCM-template-project/img/Redo.png \
ATCM-template-project/img/Refresh.png \
ATCM-template-project/img/Remove.png \
ATCM-template-project/img/Repair.png \
ATCM-template-project/img/Report.png \
ATCM-template-project/img/Retort.png \
ATCM-template-project/img/Rewind.png \
ATCM-template-project/img/SDcard.png \
ATCM-template-project/img/Sad.png \
ATCM-template-project/img/Save.png \
ATCM-template-project/img/SaveAll.png \
ATCM-template-project/img/Schedule.png \
ATCM-template-project/img/Script.png \
ATCM-template-project/img/Search.png \
ATCM-template-project/img/Shield.png \
ATCM-template-project/img/Shopping_cart.png \
ATCM-template-project/img/Silence.png \
ATCM-template-project/img/Smile.png \
ATCM-template-project/img/Sound.png \
ATCM-template-project/img/Stock_graph.png \
ATCM-template-project/img/Stop.png \
ATCM-template-project/img/Stop_sign.png \
ATCM-template-project/img/Stopwatch.png \
ATCM-template-project/img/Sum.png \
ATCM-template-project/img/Sync.png \
ATCM-template-project/img/Table.png \
ATCM-template-project/img/Target.png \
ATCM-template-project/img/Taxi.png \
ATCM-template-project/img/Terminate.png \
ATCM-template-project/img/Text.png \
ATCM-template-project/img/Text_preview.png \
ATCM-template-project/img/Thumbs_down.png \
ATCM-template-project/img/Thumbs_up.png \
ATCM-template-project/img/Toolbox.png \
ATCM-template-project/img/Top.png \
ATCM-template-project/img/Trackback.png \
ATCM-template-project/img/Trash.png \
ATCM-template-project/img/Tune.png \
ATCM-template-project/img/Turn_off.png \
ATCM-template-project/img/Twitter.png \
ATCM-template-project/img/Undo.png \
ATCM-template-project/img/Unlock.png \
ATCM-template-project/img/Up-down.png \
ATCM-template-project/img/Up.png \
ATCM-template-project/img/Update.png \
ATCM-template-project/img/Upload.png \
ATCM-template-project/img/User_group.png \
ATCM-template-project/img/View.png \
ATCM-template-project/img/Volume.png \
ATCM-template-project/img/Wallet.png \
ATCM-template-project/img/Warning.png \
ATCM-template-project/img/WifiOff.png \
ATCM-template-project/img/WifiOn.png \
ATCM-template-project/img/Wrench.png \
ATCM-template-project/img/Yellow_bookmark.png \
ATCM-template-project/img/Yellow_pin.png \
ATCM-template-project/img/Yellow_tag.png \
ATCM-template-project/img/Yes.png \
ATCM-template-project/img/Zoom.png \
ATCM-template-project/lang_table.csv \
ATCM-template-project/languages.pri \
ATCM-template-project/languages.qrc \
ATCM-template-project/page100.cpp \
ATCM-template-project/page100.h \
ATCM-template-project/page100.ui \
ATCM-template-project/pages.cpp \
ATCM-template-project/pages.h \
ATCM-template-project/plc/Alarms.st \
ATCM-template-project/plc/CEPrjSettings.4cs \
ATCM-template-project/plc/Configuration1.con \
ATCM-template-project/plc/Crosstable.gvl \
ATCM-template-project/plc/Events.st \
ATCM-template-project/plc/Fast.st \
ATCM-template-project/plc/Init.st \
ATCM-template-project/plc/Normal.st \
ATCM-template-project/plc/Project.4gh \
ATCM-template-project/plc/Resource1.cst \
ATCM-template-project/plc/Resource1.gvl \
ATCM-template-project/plc/Resource1.res \
ATCM-template-project/plc/Slow.st \
ATCM-template-project/plc/TPAC.ATHW119 \
ATCM-template-project/plc/fileview.xml \
ATCM-template-project/plc/plc.4clc \
ATCM-template-project/plc/plc.4cp \
ATCM-template-project/project.pro \
ATCM-template-project/project.pro.shared \
ATCM-template-project/resources.qrc \
ATCM-template-project/style.h \
ATCM-template-project/systemicons.qrc 
